//! The daemon-to-browser seam, checked rather than trusted (Y-124).
//!
//! [`api`](crate::api)'s DTOs and `web/src/api.ts` describe one wire shape in
//! two languages and nothing compared them: renaming a field here left every
//! Rust and TypeScript test green and the dashboard blank. So the real routes
//! render the fixture below and it is committed as TypeScript that `satisfies`
//! the types the dashboard reads with. A rename fails **here** first, because
//! the committed file stops matching what the routes now answer, and fails
//! `tsc` second, once someone regenerates it without moving `api.ts`.
//!
//! **TypeScript rather than JSON.** An imported JSON module has its string
//! literals widened to `string`, which no discriminated union accepts, so the
//! assertion has to sit where the literal is written.
//!
//! The write answers are serialised from their DTOs rather than fetched from
//! the router: those handlers `await` ssh and authorise a real tailnet caller,
//! neither of which a unit test has.
//!
//! `terminalSize` is the first entry travelling the other way — a shape the
//! *browser* writes and the daemon reads (Y-129). `satisfies` checks the same
//! thing about it, which is that the two sides spell one message identically;
//! that the daemon then accepts it is [`crate::terminal`]'s own test.

use std::path::PathBuf;
use std::sync::Arc;

use axum::body::Body;
use axum::http::Request;
use serde_json::Value;
use tower::ServiceExt as _;
use yantra_core::agent::Running;
use yantra_core::attention::{Attention, Item};
use yantra_core::doctor;
use yantra_core::heartbeat::{Heartbeat, Power};
use yantra_core::inventory::{MachineInfo, Os};
use yantra_core::sessions::{self, MachineSessions};
use yantra_core::snapshot::{Reading, Snapshot};
use yantra_core::status::{self, MachineStatus, Report, Verdict};
use yantra_core::tmux::Summary;
use yantra_core::workspace::{Listing, Unusable, Workspace};

use crate::heartbeat::{Beats, Fleet};

const GENERATED: &str = "../../web/src/contract.gen.ts";

const HEADER: &str = "\
// Generated by `just fixtures` from yantrad's own routes — do not edit.
//
// Every value here is a response the daemon really rendered, and `satisfies`
// checks it against the type the dashboard reads it with. `tsc` type-checks
// every file under `src/`, so these assertions hold without anything importing
// them. A field renamed in crates/yantrad/src/api.rs fails the Rust test that
// writes this file, and fails here once it is regenerated.
import type {
  Attention,
  Broken,
  Listed,
  Listing,
  Looked,
  Machine,
  MachineSessions,
  Opened,
  Readiness,
  Resumed,
  Spend,
  Stopped,
  TerminalSize,
  Transcript,
  Workspace,
  WorkspaceStatus,
} from './api'
";

/// Writes when `YANTRA_FIXTURES` is set and compares otherwise, so the
/// committed file cannot fall behind the routes without something going red.
#[tokio::test]
async fn the_dashboard_reads_what_the_daemon_writes() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(GENERATED);
    let rendered = render(answers().await);

    if std::env::var_os("YANTRA_FIXTURES").is_some() {
        std::fs::write(&path, &rendered).expect("the web directory is in the same checkout");
        return;
    }

    let committed = std::fs::read_to_string(&path).expect("the fixture is committed");
    assert!(
        committed == rendered,
        "web/src/contract.gen.ts no longer matches what /api answers — run `just fixtures`"
    );
}

/// Each answer beside the `web/src/api.ts` type it must satisfy. Those type
/// names are the whole of what this file restates about TypeScript.
async fn answers() -> Vec<(&'static str, &'static str, Value)> {
    let fleet = fleet().await;
    let mut out = vec![
        (
            "machines",
            "Looked<Machine[]>",
            read(&fleet, "/machines").await,
        ),
        (
            "workspaces",
            "Looked<Listed[]>",
            read(&fleet, "/workspaces").await,
        ),
        (
            "sessions",
            "Looked<MachineSessions[]>",
            read(&fleet, "/sessions").await,
        ),
        (
            "agents",
            "Looked<WorkspaceStatus>[]",
            Value::Array(agents(&fleet).await),
        ),
        (
            "readiness",
            "Looked<Readiness[]>",
            read(&fleet, "/readiness").await,
        ),
        (
            "oneReadiness",
            "Looked<Readiness>",
            read(&fleet, "/machines/cachyos-g14/readiness").await,
        ),
        (
            "attention",
            "Looked<Attention>",
            read(&fleet, "/attention").await,
        ),
        (
            "notLooked",
            "Looked<Machine[]>",
            read(&Fleet::default(), "/machines").await,
        ),
        (
            "failed",
            "Looked<Machine[]>",
            read(&broken(), "/machines").await,
        ),
    ];
    out.extend(crate::write::answers());
    out.extend(crate::terminal::answers());
    out
}

async fn read(fleet: &Fleet, path: &str) -> Value {
    let response = crate::api::router()
        .with_state(fleet.clone())
        .oneshot(
            Request::get(path)
                .body(Body::empty())
                .expect("a GET with no body is a valid request"),
        )
        .await
        .expect("the router is infallible");
    let body = axum::body::to_bytes(response.into_body(), 64 * 1024)
        .await
        .expect("the body is in memory");
    serde_json::from_slice(&body).expect("every answer is JSON")
}

/// One request per verdict, because `columns.tsx` switches on all nine — a
/// state that only ever appears in a hand-written stub is a state nothing
/// checks — and one for a machine that did not answer.
async fn agents(fleet: &Fleet) -> Vec<Value> {
    let mut out = Vec::new();
    for (name, _) in verdicts() {
        out.push(read(fleet, &format!("/workspaces/{name}/status")).await);
    }
    out.push(read(fleet, "/workspaces/unreachable/status").await);
    out
}

fn verdicts() -> Vec<(&'static str, Verdict)> {
    vec![
        ("gone", Verdict::NoSession),
        ("api", Verdict::Running),
        ("done", Verdict::Finished),
        ("halted", Verdict::Stopped),
        ("broke", Verdict::Crashed { status: 1 }),
        (
            "shot",
            Verdict::Killed {
                signal: "KILL".into(),
            },
        ),
        ("shell", Verdict::NoAgent),
        ("waiting", Verdict::AwaitingTrust),
        (
            "ghost",
            Verdict::Unclear {
                because: "the pane is alive but claude knows of no agent in that directory",
            },
        ),
    ]
}

async fn fleet() -> Fleet {
    let fleet = holding(Snapshot {
        machines: Some(Arc::new(Reading::new(Ok(vec![
            machine("n-1", "cachyos-g14", true, None),
            machine(
                "n-2",
                "bishwajeets-macbook-pro",
                false,
                Some("2026-07-07T09:00:00Z"),
            ),
            machine("n-3", "pi", true, None),
        ])))),
        workspaces: Some(Arc::new(Reading::new(Ok(Listing {
            workspaces: vec![
                workspace("api", "cachyos-g14", Some("claude")),
                workspace("site", "bishwajeets-macbook-pro", None),
            ],
            unusable: vec![unusable()],
        })))),
        sessions: Some(Arc::new(Reading::new(Ok(vec![
            MachineSessions {
                machine: "cachyos-g14".into(),
                sessions: Ok(vec![Summary {
                    name: "yantra".into(),
                    windows: 2,
                    attached: 1,
                    created: "Thu Jul 30 13:02:31 2026".into(),
                }]),
            },
            MachineSessions {
                machine: "pi".into(),
                sessions: Err(sessions::Error::Interrupted {
                    machine: "pi".into(),
                    reason: "connection timed out".into(),
                }),
            },
        ])))),
        agents: Some(Arc::new(Reading::new(Ok(status::Fleet {
            unusable: vec![unusable()],
            machines: vec![
                MachineStatus {
                    machine: "cachyos-g14".into(),
                    workspaces: verdicts()
                        .into_iter()
                        .map(|(name, _)| workspace(name, "cachyos-g14", None))
                        .collect(),
                    reports: Ok(verdicts()
                        .into_iter()
                        .map(|(name, verdict)| Report {
                            workspace: workspace(name, "cachyos-g14", None),
                            pane: None,
                            agent: matches!(verdict, Verdict::Running).then(running),
                            verdict,
                        })
                        .collect()),
                },
                MachineStatus {
                    machine: "pi".into(),
                    workspaces: vec![workspace("unreachable", "pi", None)],
                    reports: Err(status::Error::Ssh(yantra_core::ssh::Error::Transport {
                        host: "pi".into(),
                        diagnosis: "connect to host pi port 22: Connection refused".into(),
                    })),
                },
            ],
        })))),
        readiness: Some(Arc::new(Reading::new(Ok(vec![
            swept("cachyos-g14"),
            swept("bishwajeets-macbook-pro"),
        ])))),
        attention: Some(Arc::new(Reading::new(Ok(attention())))),
        // `/readiness/github` has no entry below: the type it would satisfy is
        // the card's, and the dashboard is parked (Y-174).
        github: None,
    });

    let mut beats = fleet.beats.write().await;
    beats.insert("n-1".to_owned(), Reading::new(beat(Power::Ac)));
    beats.insert(
        "n-2".to_owned(),
        Reading::new(beat(Power::Battery { percent: 42 })),
    );
    drop(beats);
    fleet
}

/// The look itself failing is the fourth state, and it is the one a page draws
/// as an empty fleet if the envelope ever stops naming it.
fn broken() -> Fleet {
    holding(Snapshot {
        machines: Some(Arc::new(Reading::new(Err(
            yantra_core::inventory::Error::Command {
                stderr: "failed to connect to local tailscaled".into(),
            },
        )))),
        ..Snapshot::default()
    })
}

fn holding(snapshot: Snapshot) -> Fleet {
    Fleet {
        model: Arc::new(tokio::sync::RwLock::new(snapshot)),
        beats: Beats::default(),
        ..Fleet::default()
    }
}

fn machine(id: &str, name: &str, online: bool, last_seen: Option<&str>) -> MachineInfo {
    MachineInfo {
        id: id.into(),
        name: name.into(),
        dns_name: format!("{name}.<tailnet>.ts.net."),
        os: Os::Linux,
        online,
        last_seen: last_seen.map(str::to_owned),
        expired: false,
        addresses: Vec::new(),
    }
}

/// A file the listing refused. It is in the fixture rather than only in a
/// hand-written stub for this file's own reason: a state nothing generated is a
/// state nothing checks, and `loaded: "no"` is the entry `web/` must narrow on.
/// Three checks rather than the nine `doctor` runs: what a page has to render
/// is one of three states beside a name and a sentence, and the ninth of those
/// tells it nothing the third did not.
fn swept(machine: &str) -> doctor::Report {
    doctor::Report {
        machine: machine.into(),
        checks: vec![
            doctor::Check {
                check: "reachable",
                state: doctor::State::Present,
                detail: "a command ran there and reported its own status".into(),
            },
            doctor::Check {
                check: "provider-auth",
                state: doctor::State::Absent,
                detail: "`gh` is installed there and no account is logged in".into(),
            },
            // The daemon fills this one in from the beats it holds, so the
            // fixture's value is the substitution's rather than the library's.
            doctor::Check {
                check: doctor::HEARTBEAT,
                state: doctor::State::Unknown,
                detail: "only the running daemon holds the beats".into(),
            },
        ],
    }
}

/// One of each list, because which list an item is in *is* its kind and the
/// band draws the two under separate headings. `notifications` is a count and
/// never a list (D6 §3.1).
fn attention() -> Attention {
    Attention {
        reviews: vec![Item {
            repo: "utopia-php/messaging".into(),
            number: 54,
            title: "feat: add the APNs adapter".into(),
            url: "https://github.com/utopia-php/messaging/pull/54".into(),
            updated_at: "2026-08-10T09:12:44Z".into(),
        }],
        issues: vec![Item {
            repo: "2002Bishwajeet/yantra".into(),
            number: 118,
            title: "the fleet page draws an empty table while nobody has looked".into(),
            url: "https://github.com/2002Bishwajeet/yantra/issues/118".into(),
            updated_at: "2026-08-11T18:09:33Z".into(),
        }],
        notifications: 7,
    }
}

fn unusable() -> Unusable {
    Unusable {
        name: "typo".into(),
        error: yantra_core::workspace::Error::Blank {
            name: "typo".into(),
            path: "/home/<user>/.config/yantra/workspaces/typo.toml".into(),
            field: "machine",
        },
    }
}

fn workspace(name: &str, machine: &str, startup: Option<&str>) -> Workspace {
    Workspace {
        name: name.into(),
        machine: machine.into(),
        repo: "/home/<user>/Github/site".into(),
        startup: startup.map(str::to_owned),
    }
}

fn beat(power: Power) -> Heartbeat {
    Heartbeat {
        sent_at: time::OffsetDateTime::from_unix_timestamp(1_785_522_600)
            .expect("a fixed, valid timestamp"),
        arch: "x86_64".into(),
        labels: vec!["gpu".into(), "docker".into()],
        free_ram_mb: 19942,
        free_disk_mb: 214003,
        cpu_busy_pct: 15,
        power,
    }
}

fn running() -> Running {
    Running {
        pid: 48213,
        cwd: "/home/<user>/Github/site".into(),
        session_id: "1f0c1a2e-4c2b-4f7a-9a1d-3f0c2b8e7d61".into(),
        status: "running".into(),
    }
}

fn render(answers: Vec<(&str, &str, Value)>) -> String {
    let mut out = HEADER.to_owned();
    for (name, ts, value) in answers {
        let json = serde_json::to_string_pretty(&value).expect("a rendered answer is JSON");
        out.push_str(&format!("\nexport const {name} = {json} satisfies {ts}\n"));
    }
    out
}
