// Generated by `just fixtures` from yantrad's own routes — do not edit.
//
// Every value here is a response the daemon really rendered, and `satisfies`
// checks it against the type the dashboard reads it with. `tsc` type-checks
// every file under `src/`, so these assertions hold without anything importing
// them. A field renamed in crates/yantrad/src/api.rs fails the Rust test that
// writes this file, and fails here once it is regenerated.
import type {
  About,
  Attention,
  Broken,
  ChatAttached,
  ChatFailure,
  ChatFrame,
  ChatNotAttached,
  Cloning,
  Connection,
  Device,
  Event,
  Joined,
  Listed,
  Listing,
  Looked,
  Machine,
  MachineSessions,
  Opened,
  Readiness,
  Repo,
  Resumed,
  Spend,
  SshIdentity,
  Stopped,
  TerminalExit,
  TerminalSize,
  ThreadEvent,
  Transcript,
  Workspace,
  WorkspaceStatus,
} from './api'

export const machines = {
  "age_seconds": 0,
  "data": [
    {
      "address": "100.64.0.1",
      "dns_name": "cachyos-g14.<tailnet>.ts.net.",
      "expired": false,
      "heartbeat": {
        "age_seconds": 0,
        "arch": "x86_64",
        "cpu_busy_pct": 15,
        "free_disk_mb": 214003,
        "free_ram_mb": 19942,
        "labels": [
          "gpu",
          "docker"
        ],
        "power": "ac"
      },
      "last_seen": null,
      "name": "cachyos-g14",
      "online": true,
      "os": "linux",
      "ownership": "yours"
    },
    {
      "address": null,
      "dns_name": "bishwajeets-macbook-pro.<tailnet>.ts.net.",
      "expired": false,
      "heartbeat": {
        "age_seconds": 0,
        "arch": "x86_64",
        "cpu_busy_pct": 15,
        "free_disk_mb": 214003,
        "free_ram_mb": 19942,
        "labels": [
          "gpu",
          "docker"
        ],
        "power": {
          "battery": {
            "percent": 42
          }
        }
      },
      "last_seen": "2026-07-07T09:00:00Z",
      "name": "bishwajeets-macbook-pro",
      "online": false,
      "os": "linux",
      "ownership": "yours"
    },
    {
      "address": null,
      "dns_name": "pi.<tailnet>.ts.net.",
      "expired": false,
      "heartbeat": null,
      "last_seen": null,
      "name": "pi",
      "online": true,
      "os": "linux",
      "ownership": "yours"
    }
  ],
  "looked": "ok"
} satisfies Looked<Machine[]>

export const workspaces = {
  "age_seconds": 0,
  "data": [
    {
      "loaded": "yes",
      "machine": "cachyos-g14",
      "name": "api",
      "repo": "/home/<user>/Github/site",
      "startup": "claude"
    },
    {
      "loaded": "yes",
      "machine": "bishwajeets-macbook-pro",
      "name": "site",
      "repo": "/home/<user>/Github/site",
      "startup": null
    },
    {
      "error": "workspace `typo` at /home/<user>/.config/yantra/workspaces/typo.toml has an empty `machine`, so nothing can open it — fill that line in or move the file aside",
      "loaded": "no",
      "name": "typo"
    }
  ],
  "looked": "ok"
} satisfies Looked<Listed[]>

export const sessions = {
  "age_seconds": 0,
  "data": [
    {
      "machine": "cachyos-g14",
      "reached": "yes",
      "sessions": [
        {
          "attached": 1,
          "created": "Thu Jul 30 13:02:31 2026",
          "created_at": 1785502951,
          "name": "yantra",
          "windows": 2
        }
      ]
    },
    {
      "error": "querying pi did not finish: connection timed out",
      "machine": "pi",
      "reached": "no"
    }
  ],
  "looked": "ok"
} satisfies Looked<MachineSessions[]>

export const agents = [
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "state": "no_session"
      },
      "workspace": "gone"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": {
        "id": "1f0c1a2e-4c2b-4f7a-9a1d-3f0c2b8e7d61",
        "pid": 48213
      },
      "status": {
        "state": "running"
      },
      "workspace": "api"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "state": "finished"
      },
      "workspace": "done"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "state": "stopped"
      },
      "workspace": "halted"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "exit_status": 1,
        "state": "crashed"
      },
      "workspace": "broke"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "signal": "KILL",
        "state": "killed"
      },
      "workspace": "shot"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "state": "no_agent"
      },
      "workspace": "shell"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "state": "awaiting_trust"
      },
      "workspace": "waiting"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "because": "the pane is alive but claude knows of no agent in that directory",
        "state": "unclear"
      },
      "workspace": "ghost"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "error": "ssh to pi failed before the command reported a status: connect to host pi port 22: Connection refused",
      "machine": "pi",
      "reached": "no",
      "workspace": "unreachable"
    },
    "looked": "ok"
  }
] satisfies Looked<WorkspaceStatus>[]

export const readiness = {
  "age_seconds": 0,
  "data": [
    {
      "checks": [
        {
          "check": "reachable",
          "detail": "a command ran there and reported its own status",
          "state": "present"
        },
        {
          "check": "provider-auth",
          "detail": "`gh` is installed there and no account is logged in",
          "state": "absent"
        },
        {
          "check": "heartbeat",
          "detail": "a beat arrived 0s ago",
          "state": "present"
        }
      ],
      "machine": "cachyos-g14"
    },
    {
      "checks": [
        {
          "check": "reachable",
          "detail": "a command ran there and reported its own status",
          "state": "present"
        },
        {
          "check": "provider-auth",
          "detail": "`gh` is installed there and no account is logged in",
          "state": "absent"
        },
        {
          "check": "heartbeat",
          "detail": "a beat arrived 0s ago",
          "state": "present"
        }
      ],
      "machine": "bishwajeets-macbook-pro"
    }
  ],
  "looked": "ok"
} satisfies Looked<Readiness[]>

export const oneReadiness = {
  "age_seconds": 0,
  "data": {
    "checks": [
      {
        "check": "reachable",
        "detail": "a command ran there and reported its own status",
        "state": "present"
      },
      {
        "check": "provider-auth",
        "detail": "`gh` is installed there and no account is logged in",
        "state": "absent"
      },
      {
        "check": "heartbeat",
        "detail": "a beat arrived 0s ago",
        "state": "present"
      }
    ],
    "machine": "cachyos-g14"
  },
  "looked": "ok"
} satisfies Looked<Readiness>

export const attention = {
  "age_seconds": 0,
  "data": {
    "issues": [
      {
        "number": 118,
        "repo": "2002Bishwajeet/yantra",
        "title": "the fleet page draws an empty table while nobody has looked",
        "updated_at": "2026-08-11T18:09:33Z",
        "url": "https://github.com/2002Bishwajeet/yantra/issues/118"
      }
    ],
    "notifications": 7,
    "reviews": [
      {
        "number": 54,
        "repo": "utopia-php/messaging",
        "title": "feat: add the APNs adapter",
        "updated_at": "2026-08-10T09:12:44Z",
        "url": "https://github.com/utopia-php/messaging/pull/54"
      }
    ]
  },
  "looked": "ok"
} satisfies Looked<Attention>

export const repos = {
  "age_seconds": 0,
  "data": [
    {
      "clone_url": "https://github.com/2002Bishwajeet/yantra.git",
      "default_branch": "main",
      "full_name": "2002Bishwajeet/yantra",
      "language": "Rust",
      "private": false,
      "pushed_at": "2026-09-05T21:14:03Z"
    },
    {
      "clone_url": "https://github.com/2002Bishwajeet/scratch.git",
      "default_branch": "main",
      "full_name": "2002Bishwajeet/scratch",
      "language": null,
      "private": true,
      "pushed_at": null
    }
  ],
  "looked": "ok"
} satisfies Looked<Repo[]>

export const github = {
  "client_id": null,
  "client_id_custom": false,
  "connected": true,
  "login": "2002Bishwajeet",
  "pending": false,
  "scopes": []
} satisfies Connection

export const disconnected = {
  "client_id": null,
  "client_id_custom": false,
  "connected": false,
  "login": null,
  "pending": false,
  "scopes": []
} satisfies Connection

export const notifications = {
  "age_seconds": 0,
  "data": [
    {
      "at": 1785522900,
      "commands": [],
      "kept": false,
      "kind": "joined",
      "logs_in_as": "biswa",
      "machine": "pi",
      "said": "pi joined, and Yantra logs in there as biswa",
      "user": "biswa",
      "workspace": null
    },
    {
      "at": 1785522840,
      "commands": [
        "sudo apt-get update; sudo apt-get install -y tmux"
      ],
      "kind": "install_stopped",
      "machine": "pi",
      "said": "pi: claude installed; tmux left for you: the package manager needs root, and sudo asks for a password or a terminal there — run `sudo apt-get update; sudo apt-get install -y tmux` on pi",
      "workspace": null
    },
    {
      "at": 1785522780,
      "commands": [],
      "kind": "relay-test",
      "machine": null,
      "said": "yantra can reach this topic",
      "workspace": null
    },
    {
      "at": 1785522720,
      "commands": [],
      "kind": "unreachable",
      "machine": "pi",
      "said": "pi is no longer online",
      "workspace": null
    },
    {
      "at": 1785522660,
      "commands": [],
      "kind": "crashed",
      "machine": "bishwajeets-macbook-pro",
      "said": "site: crashed (exit 1)",
      "workspace": "site"
    },
    {
      "at": 1785522600,
      "commands": [],
      "kind": "awaiting_trust",
      "machine": "cachyos-g14",
      "said": "api: waiting at claude's trust prompt",
      "workspace": "api"
    }
  ],
  "looked": "ok"
} satisfies Looked<Event[]>

export const notLooked = {
  "looked": "never"
} satisfies Looked<Machine[]>

export const failed = {
  "age_seconds": 0,
  "error": "`tailscale status --json` failed: failed to connect to local tailscaled",
  "looked": "failed"
} satisfies Looked<Machine[]>

export const about = {
  "built": "2026-09-06",
  "listening_on": [
    "100.64.0.1:7717",
    "[fd7a:115c:a1e0::1]:7717"
  ],
  "published": {
    "age_seconds": 1234,
    "data": {
      "newer": true,
      "version": "0.4.0"
    },
    "looked": "ok"
  },
  "relay": true,
  "tailnet": "<tailnet>.ts.net",
  "target": "aarch64-unknown-linux-musl",
  "uptime_seconds": 86412,
  "version": "0.1.0"
} satisfies About

export const sshIdentity = {
  "fingerprint": "SHA256:<fingerprint>",
  "kind": "ed25519",
  "path": "/home/<user>/.ssh/id_yantra",
  "public_key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB<key> yantra"
} satisfies SshIdentity

export const device = {
  "expires_in": 900,
  "interval": 5,
  "user_code": "WDJB-MJHT",
  "verification_uri": "https://github.com/login/device"
} satisfies Device

export const made = {
  "machine": "cachyos-g14",
  "name": "site",
  "repo": "/home/<user>/Github/site",
  "startup": "npm run dev"
} satisfies Workspace

export const opened = {
  "launched": true,
  "machine": "cachyos-g14",
  "session": "created",
  "term": "xterm-256color"
} satisfies Opened

export const stopped = {
  "ending": "Finished",
  "machine": "cachyos-g14",
  "stopped": true
} satisfies Stopped

export const resumed = {
  "machine": "cachyos-g14",
  "resumed": false,
  "term": "xterm-256color"
} satisfies Resumed

export const broken = {
  "error": "workspace `site` at /home/<user>/.config/yantra/workspaces/site.toml is not valid TOML: TOML parse error at line 2, column 7",
  "name": "site",
  "path": "/home/<user>/.config/yantra/workspaces/site.toml",
  "text": "machine = \"cachyos-g14\"\nrepo =\n"
} satisfies Broken

export const spend = {
  "as_of": "2026-08-11",
  "cost": 5.4633115,
  "fast": 0,
  "models": [
    {
      "cache_read": 4812003,
      "cache_write": 120400,
      "cost": 5.4633115,
      "input": 9412,
      "model": "claude-opus-5-20260115",
      "output": 84310,
      "responses": 66
    },
    {
      "cache_read": 4812003,
      "cache_write": 120400,
      "cost": null,
      "input": 118,
      "model": "unknown",
      "output": 640,
      "responses": 2
    }
  ],
  "path": "/home/<user>/.claude/projects/-home-<user>-Github-site/1f0c1a2e.jsonl",
  "total": {
    "cache_read": 9624006,
    "cache_write": 240800,
    "input": 9530,
    "output": 84950,
    "responses": 68
  }
} satisfies Spend

export const spendFast = {
  "as_of": "2026-08-11",
  "cost": null,
  "fast": 3,
  "models": [
    {
      "cache_read": 4812003,
      "cache_write": 120400,
      "cost": null,
      "input": 9412,
      "model": "claude-opus-5-20260115",
      "output": 84310,
      "responses": 66
    },
    {
      "cache_read": 4812003,
      "cache_write": 120400,
      "cost": null,
      "input": 118,
      "model": "unknown",
      "output": 640,
      "responses": 2
    }
  ],
  "path": "/home/<user>/.claude/projects/-home-<user>-Github-site/1f0c1a2e.jsonl",
  "total": {
    "cache_read": 9624006,
    "cache_write": 240800,
    "input": 9530,
    "output": 84950,
    "responses": 68
  }
} satisfies Spend

export const logs = {
  "path": "/home/<user>/.claude/projects/-home-<user>-Github-site/1f0c1a2e.jsonl",
  "total": 1944,
  "turns": [
    {
      "at": "2026-08-11T18:09:33.178Z",
      "text": "run the tests",
      "tools": [],
      "who": "you"
    },
    {
      "at": null,
      "text": "Running them now.",
      "tools": [
        {
          "name": "Bash",
          "target": "cargo nextest run --workspace"
        },
        {
          "name": "SendUserFile",
          "target": null
        }
      ],
      "who": "claude"
    }
  ]
} satisfies Transcript

export const joined = {
  "kept": false,
  "logs_in_as": "<user>",
  "machine": "cachyos-g14",
  "user": "<user>"
} satisfies Joined

export const joinedKept = {
  "kept": true,
  "logs_in_as": "yantra",
  "machine": "cachyos-g14",
  "user": "<user>"
} satisfies Joined

export const cloning = {
  "machine": "cachyos-g14",
  "session": "clone-yantra"
} satisfies Cloning

export const listing = {
  "access": true,
  "entries": [
    {
      "access": true,
      "kind": "dir",
      "name": "yantra",
      "origin": "https://github.com/2002Bishwajeet/yantra.git",
      "path": "/home/<user>/Github/yantra",
      "repo": true
    },
    {
      "access": true,
      "kind": "dir",
      "name": "scratch",
      "origin": null,
      "path": "/home/<user>/Github/scratch",
      "repo": false
    },
    {
      "access": false,
      "kind": "dir",
      "name": "private",
      "origin": null,
      "path": "/home/<user>/Github/private",
      "repo": false
    },
    {
      "access": true,
      "kind": "file",
      "name": "notes.md",
      "origin": null,
      "path": "/home/<user>/Github/notes.md",
      "repo": false
    }
  ],
  "machine": "cachyos-g14",
  "path": "/home/<user>/Github",
  "truncated": false
} satisfies Listing

export const terminalSize = {
  "cols": 120,
  "rows": 40,
  "term": "xterm-256color"
} satisfies TerminalSize

export const terminalExit = {
  "exit": 0
} satisfies TerminalExit

export const chatEvents = [
  {
    "payload": {
      "harness": "opencode",
      "thread": "1a2b3c4d"
    },
    "threadId": "1a2b3c4d",
    "type": "thread.started"
  },
  {
    "threadId": "1a2b3c4d",
    "type": "turn.started"
  },
  {
    "payload": {
      "delta": "Running the tests.",
      "itemId": "msg_1:1",
      "streamKind": "assistant_text"
    },
    "threadId": "1a2b3c4d",
    "type": "content.delta"
  },
  {
    "payload": {
      "itemId": "toolu_1",
      "itemType": "command_execution",
      "status": "inProgress",
      "title": "cargo test"
    },
    "threadId": "1a2b3c4d",
    "type": "item.started"
  },
  {
    "payload": {
      "detail": "Run the unit tests",
      "itemId": "toolu_1",
      "options": [
        {
          "decision": "accept",
          "label": "Accept",
          "optionId": "accept"
        },
        {
          "decision": "acceptAlways",
          "label": "Accept always",
          "optionId": "accept_always"
        },
        {
          "decision": "decline",
          "label": "Decline",
          "optionId": "decline"
        }
      ],
      "requestId": "r1",
      "requestType": "exec_command_approval",
      "title": "cargo test"
    },
    "threadId": "1a2b3c4d",
    "type": "request.opened"
  },
  {
    "payload": {
      "decision": "accept",
      "requestId": "r1",
      "requestType": "exec_command_approval"
    },
    "threadId": "1a2b3c4d",
    "type": "request.resolved"
  },
  {
    "payload": {
      "itemId": "toolu_1",
      "output": "test result: ok",
      "status": "completed"
    },
    "threadId": "1a2b3c4d",
    "type": "item.completed"
  },
  {
    "payload": {
      "maxTokens": 200000,
      "usedTokens": 29149
    },
    "threadId": "1a2b3c4d",
    "type": "thread.token-usage.updated"
  },
  {
    "payload": {
      "state": "completed",
      "stopReason": "end_turn"
    },
    "threadId": "1a2b3c4d",
    "type": "turn.completed"
  },
  {
    "payload": {
      "message": "Not logged in · Please run /login",
      "state": "failed"
    },
    "threadId": "1a2b3c4d",
    "type": "turn.completed"
  }
] satisfies ThreadEvent[]

export const chatCheckpoints = [
  {
    "payload": {
      "truncated": false,
      "turn": 1,
      "unifiedDiff": "diff --git a/a.txt b/a.txt\n--- a/a.txt\n+++ b/a.txt\n@@ -1 +1 @@\n-one\n+two\n"
    },
    "threadId": "1a2b3c4d",
    "type": "turn.diff.updated"
  },
  {
    "payload": {
      "turn": 0
    },
    "threadId": "1a2b3c4d",
    "type": "thread.reverted"
  }
] satisfies ThreadEvent[]

export const chatFailure = {
  "kind": "busy",
  "said": "a turn is running",
  "type": "error"
} satisfies ChatFailure

export const chatCheckpointFailed = {
  "kind": "checkpoint",
  "said": "git could not keep or restore a checkpoint: fatal: unable to write new index file",
  "type": "error"
} satisfies ChatFailure

export const chatNotLoggedIn = {
  "command": "opencode auth login",
  "harness": "opencode",
  "kind": "notLoggedIn",
  "machine": "cachyos-g14",
  "said": "the agent refused: Authentication required (-32000)",
  "type": "error"
} satisfies ChatFailure

export const chatAttached = {
  "path": "/tmp/yantra-chat-Y0123456789abcdef/1.png",
  "type": "attached"
} satisfies ChatAttached

export const chatNotAttached = {
  "kind": "notAnImage",
  "said": "that is not a PNG, JPEG, GIF or WebP image",
  "type": "notAttached"
} satisfies ChatNotAttached

export const chatFrames = [
  {
    "harness": "opencode",
    "mode": "auto-accept-edits",
    "text": "run the tests",
    "type": "turn"
  },
  {
    "mode": "supervised",
    "text": "and the docs",
    "type": "turn"
  },
  {
    "decision": "acceptAlways",
    "requestId": "r1",
    "type": "answer"
  },
  {
    "type": "cancel"
  },
  {
    "turn": 0,
    "type": "revert"
  }
] satisfies ChatFrame[]
