// Generated by `just fixtures` from yantrad's own routes — do not edit.
//
// Every value here is a response the daemon really rendered, and `satisfies`
// checks it against the type the dashboard reads it with. `tsc` type-checks
// every file under `src/`, so these assertions hold without anything importing
// them. A field renamed in crates/yantrad/src/api.rs fails the Rust test that
// writes this file, and fails here once it is regenerated.
import type {
  Listed,
  Looked,
  Machine,
  MachineSessions,
  Opened,
  Readiness,
  Resumed,
  Spend,
  Stopped,
  TerminalSize,
  Workspace,
  WorkspaceStatus,
} from './api'

export const machines = {
  "age_seconds": 0,
  "data": [
    {
      "dns_name": "cachyos-g14.<tailnet>.ts.net.",
      "expired": false,
      "heartbeat": {
        "age_seconds": 0,
        "arch": "x86_64",
        "cpu_busy_pct": 15,
        "free_disk_mb": 214003,
        "free_ram_mb": 19942,
        "labels": [
          "gpu",
          "docker"
        ],
        "power": "ac"
      },
      "last_seen": null,
      "name": "cachyos-g14",
      "online": true,
      "os": "linux"
    },
    {
      "dns_name": "bishwajeets-macbook-pro.<tailnet>.ts.net.",
      "expired": false,
      "heartbeat": {
        "age_seconds": 0,
        "arch": "x86_64",
        "cpu_busy_pct": 15,
        "free_disk_mb": 214003,
        "free_ram_mb": 19942,
        "labels": [
          "gpu",
          "docker"
        ],
        "power": {
          "battery": {
            "percent": 42
          }
        }
      },
      "last_seen": "2026-07-07T09:00:00Z",
      "name": "bishwajeets-macbook-pro",
      "online": false,
      "os": "linux"
    },
    {
      "dns_name": "pi.<tailnet>.ts.net.",
      "expired": false,
      "heartbeat": null,
      "last_seen": null,
      "name": "pi",
      "online": true,
      "os": "linux"
    }
  ],
  "looked": "ok"
} satisfies Looked<Machine[]>

export const workspaces = {
  "age_seconds": 0,
  "data": [
    {
      "loaded": "yes",
      "machine": "cachyos-g14",
      "name": "api",
      "repo": "/home/<user>/Github/site",
      "startup": "claude"
    },
    {
      "loaded": "yes",
      "machine": "bishwajeets-macbook-pro",
      "name": "site",
      "repo": "/home/<user>/Github/site",
      "startup": null
    },
    {
      "error": "workspace `typo` at /home/<user>/.config/yantra/workspaces/typo.toml has an empty `machine`, so nothing can open it — fill that line in or move the file aside",
      "loaded": "no",
      "name": "typo"
    }
  ],
  "looked": "ok"
} satisfies Looked<Listed[]>

export const sessions = {
  "age_seconds": 0,
  "data": [
    {
      "machine": "cachyos-g14",
      "reached": "yes",
      "sessions": [
        {
          "attached": 1,
          "created": "Thu Jul 30 13:02:31 2026",
          "name": "yantra",
          "windows": 2
        }
      ]
    },
    {
      "error": "querying pi did not finish: connection timed out",
      "machine": "pi",
      "reached": "no"
    }
  ],
  "looked": "ok"
} satisfies Looked<MachineSessions[]>

export const agents = [
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "state": "no_session"
      },
      "workspace": "gone"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": {
        "id": "1f0c1a2e-4c2b-4f7a-9a1d-3f0c2b8e7d61",
        "pid": 48213
      },
      "status": {
        "state": "running"
      },
      "workspace": "api"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "state": "finished"
      },
      "workspace": "done"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "state": "stopped"
      },
      "workspace": "halted"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "exit_status": 1,
        "state": "crashed"
      },
      "workspace": "broke"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "signal": "KILL",
        "state": "killed"
      },
      "workspace": "shot"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "state": "no_agent"
      },
      "workspace": "shell"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "state": "awaiting_trust"
      },
      "workspace": "waiting"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "machine": "cachyos-g14",
      "reached": "yes",
      "session": null,
      "status": {
        "because": "the pane is alive but claude knows of no agent in that directory",
        "state": "unclear"
      },
      "workspace": "ghost"
    },
    "looked": "ok"
  },
  {
    "age_seconds": 0,
    "data": {
      "error": "ssh to pi failed before the command reported a status: connect to host pi port 22: Connection refused",
      "machine": "pi",
      "reached": "no",
      "workspace": "unreachable"
    },
    "looked": "ok"
  }
] satisfies Looked<WorkspaceStatus>[]

export const readiness = {
  "age_seconds": 0,
  "data": [
    {
      "checks": [
        {
          "check": "reachable",
          "detail": "a command ran there and reported its own status",
          "state": "present"
        },
        {
          "check": "provider-auth",
          "detail": "`gh` is installed there and no account is logged in",
          "state": "absent"
        },
        {
          "check": "heartbeat",
          "detail": "a beat arrived 0s ago",
          "state": "present"
        }
      ],
      "machine": "cachyos-g14"
    },
    {
      "checks": [
        {
          "check": "reachable",
          "detail": "a command ran there and reported its own status",
          "state": "present"
        },
        {
          "check": "provider-auth",
          "detail": "`gh` is installed there and no account is logged in",
          "state": "absent"
        },
        {
          "check": "heartbeat",
          "detail": "a beat arrived 0s ago",
          "state": "present"
        }
      ],
      "machine": "bishwajeets-macbook-pro"
    }
  ],
  "looked": "ok"
} satisfies Looked<Readiness[]>

export const oneReadiness = {
  "age_seconds": 0,
  "data": {
    "checks": [
      {
        "check": "reachable",
        "detail": "a command ran there and reported its own status",
        "state": "present"
      },
      {
        "check": "provider-auth",
        "detail": "`gh` is installed there and no account is logged in",
        "state": "absent"
      },
      {
        "check": "heartbeat",
        "detail": "a beat arrived 0s ago",
        "state": "present"
      }
    ],
    "machine": "cachyos-g14"
  },
  "looked": "ok"
} satisfies Looked<Readiness>

export const notLooked = {
  "looked": "never"
} satisfies Looked<Machine[]>

export const failed = {
  "age_seconds": 0,
  "error": "`tailscale status --json` failed: failed to connect to local tailscaled",
  "looked": "failed"
} satisfies Looked<Machine[]>

export const made = {
  "machine": "cachyos-g14",
  "name": "site",
  "repo": "/home/<user>/Github/site",
  "startup": "npm run dev"
} satisfies Workspace

export const opened = {
  "launched": true,
  "machine": "cachyos-g14",
  "session": "created",
  "term": "xterm-256color"
} satisfies Opened

export const stopped = {
  "ending": "Finished",
  "machine": "cachyos-g14",
  "stopped": true
} satisfies Stopped

export const resumed = {
  "machine": "cachyos-g14",
  "resumed": false,
  "term": "xterm-256color"
} satisfies Resumed

export const spend = {
  "as_of": "2026-08-11",
  "cost": 5.4633115,
  "fast": 0,
  "models": [
    {
      "cost": 5.4633115,
      "model": "claude-opus-5-20260115",
      "responses": 66
    },
    {
      "cost": null,
      "model": "unknown",
      "responses": 2
    }
  ],
  "path": "/home/<user>/.claude/projects/-home-<user>-Github-site/1f0c1a2e.jsonl",
  "total": {
    "cache_read": 9624006,
    "cache_write": 240800,
    "input": 9530,
    "output": 84950,
    "responses": 68
  }
} satisfies Spend

export const spendFast = {
  "as_of": "2026-08-11",
  "cost": null,
  "fast": 3,
  "models": [
    {
      "cost": null,
      "model": "claude-opus-5-20260115",
      "responses": 66
    },
    {
      "cost": null,
      "model": "unknown",
      "responses": 2
    }
  ],
  "path": "/home/<user>/.claude/projects/-home-<user>-Github-site/1f0c1a2e.jsonl",
  "total": {
    "cache_read": 9624006,
    "cache_write": 240800,
    "input": 9530,
    "output": 84950,
    "responses": 68
  }
} satisfies Spend

export const terminalSize = {
  "cols": 120,
  "rows": 40,
  "term": "xterm-256color"
} satisfies TerminalSize
